import type { Member, Project, Series, Task } from '../../lib/api.ts';
import { WorkPicker } from './WorkPicker.tsx';
export function OwnerField({members,current,name}:{members:Member[]|null;current:string|null;name?:string|null}){return <div className="field"><label htmlFor="record-owner">Owner</label>{members?<select id="record-owner" name="ownerId" defaultValue={current??''}><option value="">No owner</option>{current&&!members.some(m=>m.userId===current)?<option value={current}>{name??'Current owner'}</option>:null}{members.filter(m=>m.status==='active'||m.userId===current).map(m=><option key={m.userId} value={m.userId}>{m.name||m.email}</option>)}</select>:<><input type="hidden" name="ownerId" value={current??''}/><p>Members could not be read. The current owner is kept.</p></>}</div>;}
export function TaskFields({task,project,members}:{task:Task;project:Project|null;members:Member[]|null}){return <>
 <label className="field">Task<input name="title" required maxLength={200} defaultValue={task.title}/></label>
 <div className="row"><OwnerField members={members} current={task.ownerId} name={task.ownerName}/><label className="field">Due<input type="date" name="due" defaultValue={task.due??''}/></label></div>
 {task.parentId?<><input type="hidden" name="projectId" value={task.projectId??''}/><p>Project follows the parent task.</p></>:<WorkPicker initial={task.projectId} initialLabel={project?.name}/>}
 <label className="field">Details<textarea name="body" maxLength={5000} defaultValue={task.body}/></label></>;}
export function ProjectFields({project}:{project?:Project}){return <><label className="field">Name<input name="name" required maxLength={120} defaultValue={project?.name}/></label><label className="field">What it is for<textarea name="description" maxLength={2000} defaultValue={project?.description}/></label>{project?<><div className="field"><label htmlFor="project-stage">Stage</label><select id="project-stage" name="stage" defaultValue={project.stage}><option value="idea">Idea</option><option value="underway">Underway</option></select></div><label><input type="checkbox" name="archived" defaultChecked={project.state==='archived'}/> Archived</label></>:null}</>;}
export function SeriesFields({series,members,ownerId,project}:{series?:Series;members:Member[]|null;ownerId:string;project?:Project|null}){return <>
 <label className="field">Recurring task<input name="title" maxLength={200} required defaultValue={series?.title}/></label>
 <OwnerField members={members} current={series?series.ownerId:ownerId}/><WorkPicker initial={series?.projectId??project?.id} initialLabel={project?.name}/>
 <div className="field"><label htmlFor="series-repeat">Repeat</label><select id="series-repeat" name="recurrence" defaultValue={series?.recurrence??'monthly'}><option value="weekdays">Every weekday</option><option value="monthly">Every month</option><option value="quarterly">Every quarter</option><option value="yearly">Every year</option><option value="custom">Every N months</option></select></div>
 <label className="field">N months (for custom repeat)<input name="everyMonths" type="number" min={1} max={120} defaultValue={series?.everyMonths??1}/></label>
 <div className="row"><label className="field">First period starts<input name="anchor" type="date" required defaultValue={series?.anchor}/></label><label className="field">Due days after period ends<input name="dueOffsetDays" type="number" min={-366} max={366} required defaultValue={series?.dueOffsetDays??0}/></label></div>
 <label><input type="checkbox" name="evidenceRequired" defaultChecked={series?.evidenceRequired}/> Evidence required to complete</label>
 <label className="field">Details<textarea name="body" maxLength={5000} defaultValue={series?.body}/></label>
 {series?<label><input type="checkbox" name="paused" defaultChecked={!!series.pausedAt}/> Pause new occurrences</label>:null}<p className="muted">Changes to this rule apply to future occurrences. Existing tasks keep their details.</p></>;}
