import assert from 'node:assert/strict';
import { after, before, test } from 'node:test';
import { randomUUID } from 'node:crypto';
import { databaseUrl, freshDatabase, type Harness } from '@captain/db/test';
import { withTenant } from '@captain/db';
import { NotesService } from './service.ts';
let db: Harness;
before(async () => { if (databaseUrl) db = await freshDatabase(); }); after(async () => { await db?.close(); });
const it = (name: string, fn: () => Promise<void>) => test(name, { skip: !databaseUrl && 'DATABASE_URL not set' }, fn);
it('notes are plain text with checked links, listed newest first, archived rather than deleted, and tenant-scoped', async () => {
 const [org] = await db.owner`insert into organisations (name) values ('Notes tenant') returning id`; const [other] = await db.owner`insert into organisations (name) values ('Other') returning id`;
 const [u, s] = await db.owner`insert into users (email) values (${randomUUID() + '@example.test'}), (${randomUUID() + '@example.test'}) returning id`;
 await db.owner`insert into memberships (organisation_id, user_id, role) values (${org!.id}, ${u!.id}, 'owner'), (${other!.id}, ${s!.id}, 'owner')`;
 const actor = { userId: String(u!.id), requestId: randomUUID() }; const stranger = { userId: String(s!.id), requestId: randomUUID() };
 const events: unknown[] = []; const notes = new NotesService(db.app, async (_tx, o, event, data) => { events.push([o, event, data]); });
 const [project] = await withTenant(db.app, { organisationId: String(org!.id), userId: actor.userId }, tx => tx`insert into projects (organisation_id, name, created_by) values (${org!.id}, 'Cans', ${actor.userId}) returning id`);
 const note = await notes.create(actor, String(org!.id), { title: 'Call with supplier', body: 'Agreed 2,000 cans for October. They send a quote Friday.', projectId: String(project!.id) });
 assert.equal(note.projectName, 'Cans'); assert.equal(note.authorId, actor.userId); assert.deepEqual(events.map(e => (e as unknown[])[1]), ['note.saved']);
 await assert.rejects(notes.create(actor, String(org!.id), { body: 'x', taskId: randomUUID() }), { code: 'link_missing' });
 await assert.rejects(notes.create(actor, String(org!.id), { body: '', title: 'Empty' }));
 const updated = await notes.update(actor, String(org!.id), note.id, { title: 'Call with supplier', body: 'Agreed 2,500 cans for October.', projectId: null });
 assert.equal(updated.projectId, null); assert.equal(events.length, 2);
 const second = await notes.create(actor, String(org!.id), { body: 'Second note.' });
 assert.deepEqual((await notes.list(actor, String(org!.id))).map(n => n.id), [second.id, note.id]);
 await notes.archive(actor, String(org!.id), second.id);
 assert.deepEqual((await notes.list(actor, String(org!.id))).map(n => n.id), [note.id]); assert.equal((await notes.list(actor, String(org!.id), { archived: true })).length, 2);
 await assert.rejects(notes.get(stranger, String(org!.id), note.id), { status: 404 });
 await assert.rejects(notes.get(actor, String(other!.id), note.id), { status: 404 });
 assert.equal((await withTenant(db.app, { organisationId: String(other!.id), userId: stranger.userId }, tx => tx`select id from notes`)).length, 0);
});
