import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createNewStorage,createNewThread,parseCreateDraft,validCreate,type CreateDraft } from './create.ts';
import { createDraftStorage,type WebStorage } from './storage.ts';
import { createThreadCalls,type Result } from './api.ts';
import type { ApiClient,ApiOutcome,Parse } from '../auth/contracts.ts';
import { threadFixture,tid,tagId } from '../../harness/thread-fixtures.ts';
import { createOptions,parseTagPage } from './options.ts';
import { createThreadControls } from './thread-controls.ts';
const uuid=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const scope={userId:uuid(1),organisationId:uuid(2),epoch:'one'},other=uuid(3),instant='2026-10-01T00:00:00.000Z';
function setup(){
 const values=new Map<string,string>(),raw:WebStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>{values.set(k,v);},removeItem:k=>{values.delete(k);},key:i=>[...values.keys()][i]??null,get length(){return values.size;}},store=createNewStorage(()=>raw);
 let current:typeof scope|null=scope,now=0,id=500,failure:ApiOutcome<never>|null=null,hold:(()=>Promise<void>)|null=null;
 const requests:{method:string;path:string;body:any;token:string|null}[]=[],opened:string[]=[];const f=threadFixture();
 const request=async<T>(method:string,path:string,token:string|null,body:any,parse:Parse<T>):Promise<ApiOutcome<T>>=>{
  requests.push({method,path,body,token});if(hold)await hold();if(failure)return failure;const u=new URL(path,'https://example.test');let value:unknown;
  if(method==='POST'&&u.pathname.endsWith('/threads'))value={...f.detail,thread:{...f.detail.thread,id:body.id,kind:body.kind,title:body.title??body.message.body},...(body.kind==='private'?{participants:[{userId:scope.userId,name:'Sam',addedAt:instant},...body.participantIds.map((userId:string)=>({userId,name:'Pat',addedAt:instant}))]}:{})};
  else if(u.pathname.endsWith('/members'))value={members:[{userId:scope.userId,name:'Sam',email:'sam@example.test',role:'member',status:'active',since:instant},{userId:other,name:'Pat',email:'pat@example.test',role:'member',status:'active',since:instant}]};
  else if(u.pathname.endsWith('/tags'))value={tags:[{id:tagId,name:'Summer',createdAt:instant,updatedAt:instant,ownerId:null,startsOn:null,endsOn:null,createdBy:null,revision:1,archivedAt:null}],nextOffset:null};
  else if(u.pathname.includes('/tags/')){assert.equal(method==='DELETE'?Number(u.searchParams.get('expectedRevision')):body.expectedRevision,f.detail.thread.revision);f.detail.tags=method==='DELETE'?[]:[{id:tagId,name:'Summer'}];f.detail.thread.revision++;value=f.detail;}
  else if(u.pathname.endsWith('/messages'))value={thread:{id:tid,revision:f.detail.thread.revision,lastSeq:65,lastChange:65},messages:f.messages.slice(0,50),hasMore:true};
  else value=f.detail;try{return {ok:true,value:parse(value)};}catch{return {ok:false,kind:'unavailable',status:200};}
 };
 const client:ApiClient={get:(p,t,parse)=>request('GET',p,t,undefined,parse),post:(p,t,b,parse)=>request('POST',p,t,b,parse),patch:(p,t,b,parse)=>request('PATCH',p,t,b,parse),delete:(p,t,parse)=>request('DELETE',p,t,undefined,parse)};
 const calls=createThreadCalls(client,{scope:()=>current,sessionEnded(){current=null;},reconcile(){}});
 const create=()=>createNewThread(calls,scope,store,()=>now,()=>uuid(id++),id=>opened.push(id));
 return {raw,values,store,calls,requests,opened,create,f,time:(n:number)=>{now=n;},fail:(f:typeof failure)=>{failure=f;},hold:(f:typeof hold)=>{hold=f;},scope:(s:typeof current)=>{current=s;},now:()=>now};
}
test('topic creation sends exactly one atomic first-message request without private fields',async()=>{const f=setup(),c=f.create();c.edit({body:'  Packaging ready  '});await c.send();assert.equal(f.requests.length,1);const request=f.requests[0]!;assert.equal(request.token,null);assert.deepEqual(Object.keys(request.body).sort(),['id','kind','message']);assert.equal(request.body.message.body,'Packaging ready');assert.deepEqual(f.opened,[request.body.id]);assert.equal(f.values.size,0);});
test('unknown private creation locks all choices and remount retries both original IDs and payload',async()=>{const f=setup(),c=f.create();c.edit({private:true,title:'Costs',body:'Review privately',participantIds:[other]});f.fail({ok:false,kind:'unavailable',status:503});await c.send();const first=f.requests[0]!.body;c.edit({title:'Changed',body:'Changed',participantIds:[]});assert.equal(c.snapshot().draft.title,'Costs');c.dispose();const again=f.create();assert.equal(f.requests.length,1);assert.equal(again.snapshot().draft.locked,true);f.fail(null);await again.send();assert.deepEqual(f.requests[1]!.body,first);assert.equal(f.values.size,0);});
test('429 preserves IDs while edits remain recoverable, including empty text; never automatically retries',async()=>{const f=setup(),c=f.create();f.fail({ok:false,kind:'unavailable',status:429,retryAfter:5});c.edit({body:'First'});await c.send();const first=f.requests[0]!.body;c.edit({body:''});c.dispose();const again=f.create();assert.equal(again.snapshot().draft.body,'');again.edit({body:'Second'});await again.send();assert.equal(f.requests.length,1);f.time(6000);f.fail(null);await again.send();assert.equal(f.requests[1]!.body.id,first.id);assert.equal(f.requests[1]!.body.message.id,first.message.id);assert.equal(f.requests[1]!.body.message.body,'Second');});
test('thread_id_unavailable survives remount and requires explicit replacement IDs',async()=>{const f=setup(),c=f.create();c.edit({body:'Keep my text'});f.fail({ok:false,kind:'refused',status:409,code:'thread_id_unavailable'});await c.send();const old=c.snapshot().draft;assert.match(c.snapshot().message,/ID cannot/);c.dispose();const again=f.create();await again.send();assert.equal(f.requests.length,1);again.newIds();assert.notEqual(again.snapshot().draft.id,old.id);assert.notEqual(again.snapshot().draft.messageId,old.messageId);assert.equal(again.snapshot().draft.body,old.body);});
test('storage refusal prevents creation; malformed drafts and other people are cleared',async()=>{const f=setup();const unavailable=createNewThread(f.calls,scope,createNewStorage(()=>null),()=>0,()=>uuid(50),()=>{});unavailable.edit({body:'Do not lose this'});await unavailable.send();assert.equal(f.requests.length,0);f.values.set(`captain.pending-thread.${scope.userId}.${scope.organisationId}.new`,'{"bad":true}');assert.equal(f.store.load(scope),null);assert.equal(f.values.size,0);const c=f.create();f.fail({ok:false,kind:'unavailable',status:503});c.edit({body:'pending'});await c.send();createDraftStorage(()=>f.raw).person(other);assert.equal(f.values.size,0);});
test('scope switches hide late creates, 404 clears pending data, and signout clears creates',async()=>{const f=setup(),c=f.create();let release!:()=>void;f.hold(()=>new Promise<void>(resolve=>{release=resolve;}));c.edit({body:'Hold'});const send=c.send();await c.send();assert.equal(f.requests.length,1);f.scope({...scope,organisationId:other});release();await send;assert.equal(f.opened.length,0);assert.equal(f.values.size,1);f.scope(scope);f.hold(null);f.fail({ok:false,kind:'refused',status:404,code:'not_found'});const again=f.create();await again.send();assert.equal(f.values.size,0);assert.equal(again.snapshot().lost,true);});
test('private input is bounded to 49 distinct other members and 80 UTF-16-unit title',()=>{const f=setup(),c=f.create();c.edit({private:true,body:'Hello',title:'😀'.repeat(40)});assert.equal(validCreate(c.snapshot().draft),true);c.edit({title:'😀'.repeat(41)});assert.equal(validCreate(c.snapshot().draft),false);c.edit({participantIds:Array.from({length:50},(_,i)=>uuid(i+10))});assert.equal(c.snapshot().draft.participantIds.length,0);assert.throws(()=>parseCreateDraft({...c.snapshot().draft,participantIds:[other,other]}));});
test('member choices are readable for a member, exclude self, and stale choices never enter a new scope',async()=>{const f=setup(),c=createOptions(f.calls,scope,'members',f.now);await c.load();assert.deepEqual(c.snapshot().rows.map(m=>m.userId),[other]);assert.equal(f.requests[0]!.path,`/v1/organisations/${scope.organisationId}/members`);const stale=createOptions(f.calls,scope,'members',f.now);let release!:()=>void;f.hold(()=>new Promise<void>(r=>{release=r;}));const pending=stale.load();f.scope({...scope,organisationId:other});release();await pending;assert.equal(stale.snapshot().rows.length,0);});
test('tag pages reject extras and duplicates, exclude archived choices and preserve bounded cursor',()=>{const tag={id:tagId,name:'Summer',createdAt:instant,updatedAt:instant,ownerId:null,startsOn:null,endsOn:null,createdBy:null,revision:1,archivedAt:null};assert.deepEqual(parseTagPage({tags:[{...tag,archivedAt:instant}],nextOffset:50}),{tags:[],nextOffset:50});assert.throws(()=>parseTagPage({tags:[{...tag,threadIds:[tid]}],nextOffset:null}));assert.throws(()=>parseTagPage({tags:[tag,tag],nextOffset:null}));});
test('tag changes use current thread revision and reconcile detail',async()=>{const f=setup(),c=createThreadControls(f.calls,scope,tid,f.now,()=>{},()=>{});await c.load();await c.mutate({kind:'tag',tagId,attached:false,expectedRevision:1});assert.equal(c.snapshot().detail?.tags.length,0);assert.equal(c.snapshot().detail?.thread.revision,2);await c.mutate({kind:'tag',tagId,attached:true,expectedRevision:2});assert.equal(c.snapshot().detail?.tags[0]?.id,tagId);assert.match(c.snapshot().message,/confirmed/);});

test('stale tag revision reads current state and requires another explicit choice',async()=>{const f=setup();let writes=0;const calls={...f.calls,async mutate(){writes++;f.f.detail.thread.revision++;return {kind:'error' as const,status:409,code:'stale_revision',retryAfter:0,uncertain:false};}};const c=createThreadControls(calls,scope,tid,f.now,()=>{},()=>{});await c.load();await c.mutate({kind:'tag',tagId,attached:false,expectedRevision:1});assert.equal(writes,1);assert.equal(c.snapshot().detail?.thread.revision,2);assert.equal(c.snapshot().detail?.tags.length,1);assert.match(c.snapshot().message,/changed/);});
